In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/drive/MyDrive/BCG_GENAI/kamt_cleaned.csv")
df.head(10)

,company,year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow from Operating Activities,Total Revenue Growth (%),Net Income Growth (%),Total Assets Growth (%),Total Liabilities Growth (%),Cash Flow from Operating Activities Growth (%),Average Assets
0,apple,21,365817.0,9468.0,351002.0,287912.0,104038.0,NaN,NaN,NaN,NaN,NaN,352113.333333
1,apple,22,394328.0,99803.0,352755.0,302083.0,122151.0,7.793788,954.108576,0.499427,4.921990,17.409985,352113.333333
2,apple,23,383285.0,96995.0,352583.0,290437.0,110543.0,-2.800461,-2.813543,-0.048759,-3.855232,-9.502992,352113.333333
3,microsoft,21,168088.0,61271.0,333779.0,191791.0,7674.0,NaN,NaN,NaN,NaN,NaN,260746.333333
4,microsoft,22,198270.0,72738.0,36484.0,198298.0,89035.0,17.956071,18.715216,-89.069414,3.392756,1060.216315,260746.333333
5,microsoft,23,211915.0,72361.0,411976.0,205753.0,87582.0,6.882030,-0.518299,1029.196360,3.759493,-1.631942,260746.333333
6,tesla,21,53823.0,5644.0,62131.0,30548.0,11497.0,NaN,NaN,NaN,NaN,NaN,78353.333333
7,tesla,22,81462.0,12587.0,82338.0,6344.0,14724.0,51.351653,123.015592,32.523217,-79.232683,28.068192,78353.333333
8,tesla,23,48256.0,2614.0,90591.0,38409.0,5578.0,-40.762564,-79.232542,10.023319,505.438209,-62.116273,78353.333333

In [17]:
df

,company,year,Total Revenue,Net Income,Total Assets,Total Revenue Growth (%),Net Income Growth (%),Average Assets
0,apple,21,365817,9468,351002,NaN,NaN,352113.33
1,apple,22,394328,99803,352755,7.79,954.10,352113.33
2,apple,23,383285,96995,352583,-2.80,-2.81,352113.33
3,microsoft,21,168088,61271,333779,NaN,NaN,260746.33
4,microsoft,22,198270,72738,36484,17.96,18.71,260746.33
5,microsoft,23,211915,72361,411976,6.88,-0.52,260746.33
6,tesla,21,53823,5644,62131,NaN,NaN,78353.33
7,tesla,22,81462,12587,82338,51.35,123.01,78353.33
8,tesla,23,48256,2614,90591,-40.76,-79.23,78353.33

In [ ]:
def get_response(user_query):
  if "revenue" in user_query:
    company=extract_company(user_query)
    year=extract_year(user_query)

In [20]:
import pandas as pd
import re

# Load the data into a DataFrame
data = {
    "company": ["apple", "apple", "apple", "microsoft", "microsoft", "microsoft", "tesla", "tesla", "tesla"],
    "year": [21, 22, 23, 21, 22, 23, 21, 22, 23],
    "Total Revenue": [365817, 394328, 383285, 168088, 198270, 211915, 53823, 81462, 48256],
    "Net Income": [9468, 99803, 96995, 61271, 72738, 72361, 5644, 12587, 2614],
    "Total Assets": [351002, 352755, 352583, 333779, 36484, 411976, 62131, 82338, 90591],
    "Total Revenue Growth (%)": [None, 7.79, -2.80, None, 17.96, 6.88, None, 51.35, -40.76],
    "Net Income Growth (%)": [None, 954.10, -2.81, None, 18.71, -0.52, None, 123.01, -79.23],
    "Average Assets": [352113.33, 352113.33, 352113.33, 260746.33, 260746.33, 260746.33, 78353.33, 78353.33, 78353.33],
}
df = pd.DataFrame(data)

def get_response(user_query):
    # Normalize the query to lowercase and strip extra spaces
    query = user_query.strip().lower()

    # Handle common typos by using regex replacements
    query = handle_typos(query)

    # Check if the query is asking for total revenue
    if "revenue" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            revenue = df[(df["company"] == company) & (df["year"] == year)]["Total Revenue"].values
            if revenue.size > 0:
                return f"The total revenue of {company.capitalize()} in {year} is ${revenue[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."

    # Check if the query is asking for net income
    elif "income" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            net_income = df[(df["company"] == company) & (df["year"] == year)]["Net Income"].values
            if net_income.size > 0:
                return f"The net income of {company.capitalize()} in {year} is ${net_income[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."

    # Check if the query is asking for total assets
    elif "assets" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            total_assets = df[(df["company"] == company) & (df["year"] == year)]["Total Assets"].values
            if total_assets.size > 0:
                return f"The total assets of {company.capitalize()} in {year} are ${total_assets[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."

    # Check if the query is asking for average assets
    elif "average assets" in query:
        company = extract_company(query)
        if company:
            avg_assets = df[df["company"] == company]["Average Assets"].mean()
            return f"The average assets of {company.capitalize()} are ${avg_assets:.2f} million."

    else:
        return "Sorry, I didn't understand that question. Please try again."

def extract_company(query):
    # Define the companies using regex patterns
    companies = ["apple", "microsoft", "tesla"]
    for company in companies:
        if re.search(r'\b' + company + r'\b', query):
            return company
    return None

def extract_year(query):
    # Define regex for extracting years (21, 2021, 22, 2022, 23, 2023)
    year_pattern = r'\b(21|2021|22|2022|23|2023)\b'
    match = re.search(year_pattern, query)
    if match:
        return int(match.group(0))  # Return the matched year as integer
    return None

def handle_typos(query):
    # Common typo fixes using regex replacements
    query = re.sub(r"\brevnue\b", "revenue", query)  # fix "revenue" typo
    query = re.sub(r"\bnet income\b", "net income", query)  # fix "net income" typo
    query = re.sub(r"\bteh\b", "the", query)  # fix "the" typo
    query = re.sub(r"\bassets\b", "total assets", query)  # fix common shorthand for assets
    return query

# Command-line chatbot
if __name__ == "__main__":
    print("Welcome to the Financial Analysis Chatbot!")
    print("You can ask questions like:")
    print("'What is the total revenue of Apple in 21?'")
    print("'How much was the net income of Microsoft in 22?'")
    print("'What is the average assets of Tesla?'")

    while True:
        user_query = input("Enter your query (or type 'exit' to quit): ")
        if user_query.lower() in ["exit", "quit"]:
            print("Goodbye!")
            break
        response = get_response(user_query)
        print(response)

Welcome to the Financial Analysis Chatbot!
You can ask questions like:
'What is the total revenue of Apple in 21?'
'How much was the net income of Microsoft in 22?'
'What is the average assets of Tesla?'
Enter your query (or type 'exit' to quit): tesla revenue 21
The total revenue of Tesla in 21 is $53823 million.
Enter your query (or type 'exit' to quit): apple net income 23
The net income of Apple in 23 is $96995 million.
Enter your query (or type 'exit' to quit): average asset microsoft 2023
Sorry, I didn't understand that question. Please try again.
Enter your query (or type 'exit' to quit): average assets microsoft 2023
Sorry, I don't have data for that year or company.
Enter your query (or type 'exit' to quit): average asset microsoft
Sorry, I didn't understand that question. Please try again.
Enter your query (or type 'exit' to quit): average assets microsoft
None
Enter your query (or type 'exit' to quit): average assets tesla
None
Enter your query (or type 'exit' to quit): assets tesla 23
The total assets of Tesla in 23 are $90591 million.

KeyboardInterrupt: Interrupted by user

**UI INMPROVEMENT**

In [21]:
!pip install ipywidgets pandas

Requirement already satisfied: ipywidgets in /usr/local/lib/python3.10/dist-packages (7.7.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (5.5.6)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (0.2.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (5.7.1)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (3.6.10)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (7.34.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ipywidgets) (3.0.13)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets) (6.1.12)
Requirement already satisfied: tornado>=4.2 in /usr/local/lib/python3.10/dist-packages (from ipykernel>=4.5.1->ipywidgets) (6.3.3)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (75.1.0)
Collecting jedi>=0.16 (from ipython>=4.0.0->ipywidgets)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (3.0.48)
Requirement already satisfied: pygments in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.10/dist-packages (from ipython>=4.0.0->ipywidgets) (4.9.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.10/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets) (6.5.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.10/dist-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets) (0.8.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (3.1.4)
Requirement already satisfied: pyzmq<25,>=17 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (23.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (5.7.2)
Requirement already satisfied: nbformat in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (7.16.4)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.6.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.21.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.10/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.1.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.10/dist-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets) (0.2.13)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.10/dist-packages (from jupyter-core>=4.6.1->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (4.3.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.10/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (3.0.2)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (24.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.5.1)
Requirement already satisfied: tinycss2 in /usr/local/lib/python3.10/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (2.20.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.10/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (4.23.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.10/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (21.2.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (0.21.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.10/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.24.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (2.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (2.22)
Requirement already satisfied: anyio<4,>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (3.7.1)
Requirement already satisfied: websocket-client in /usr/local/lib/python3.10/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.8.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<4,>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets) (1.2.2)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.2 MB/s eta 0:00:00
Installing collected packages: jedi
Successfully installed jedi-0.19.2

In [22]:
import pandas as pd
import re
import ipywidgets as widgets
from IPython.display import display

# Load the data into a DataFrame
data = {
    "company": ["apple", "apple", "apple", "microsoft", "microsoft", "microsoft", "tesla", "tesla", "tesla"],
    "year": [21, 22, 23, 21, 22, 23, 21, 22, 23],
    "Total Revenue": [365817, 394328, 383285, 168088, 198270, 211915, 53823, 81462, 48256],
    "Net Income": [9468, 99803, 96995, 61271, 72738, 72361, 5644, 12587, 2614],
    "Total Assets": [351002, 352755, 352583, 333779, 36484, 411976, 62131, 82338, 90591],
    "Total Revenue Growth (%)": [None, 7.79, -2.80, None, 17.96, 6.88, None, 51.35, -40.76],
    "Net Income Growth (%)": [None, 954.10, -2.81, None, 18.71, -0.52, None, 123.01, -79.23],
    "Average Assets": [352113.33, 352113.33, 352113.33, 260746.33, 260746.33, 260746.33, 78353.33, 78353.33, 78353.33],
}
df = pd.DataFrame(data)

# Function to process user query
def get_response(user_query):
    query = user_query.strip().lower()
    query = handle_typos(query)

    if "revenue" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            revenue = df[(df["company"] == company) & (df["year"] == year)]["Total Revenue"].values
            if revenue.size > 0:
                return f"The total revenue of {company.capitalize()} in {year} is ${revenue[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."
    elif "income" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            net_income = df[(df["company"] == company) & (df["year"] == year)]["Net Income"].values
            if net_income.size > 0:
                return f"The net income of {company.capitalize()} in {year} is ${net_income[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."
    elif "assets" in query:
        company = extract_company(query)
        year = extract_year(query)
        if company and year:
            total_assets = df[(df["company"] == company) & (df["year"] == year)]["Total Assets"].values
            if total_assets.size > 0:
                return f"The total assets of {company.capitalize()} in {year} are ${total_assets[0]} million."
            else:
                return "Sorry, I don't have data for that year or company."
    elif "average assets" in query:
        company = extract_company(query)
        if company:
            avg_assets = df[df["company"] == company]["Average Assets"].mean()
            return f"The average assets of {company.capitalize()} are ${avg_assets:.2f} million."
    else:
        return "Sorry, I didn't understand that question. Please try again."

def extract_company(query):
    companies = ["apple", "microsoft", "tesla"]
    for company in companies:
        if re.search(r'\b' + company + r'\b', query):
            return company
    return None

def extract_year(query):
    year_pattern = r'\b(21|2021|22|2022|23|2023)\b'
    match = re.search(year_pattern, query)
    if match:
        return int(match.group(0))
    return None

def handle_typos(query):
    query = re.sub(r"\brevnue\b", "revenue", query)
    query = re.sub(r"\bnet income\b", "net income", query)
    query = re.sub(r"\bteh\b", "the", query)
    query = re.sub(r"\bassets\b", "total assets", query)
    return query

# Create the widgets for UI
user_input = widgets.Text(
    description="Enter query:",
    placeholder="Type your query here...",
    layout=widgets.Layout(width="80%")
)

output_area = widgets.Output()

# Function to update the output based on the user input
def on_submit(change):
    with output_area:
        output_area.clear_output()
        response = get_response(user_input.value)
        print(response)

user_input.observe(on_submit, names='value')

# Display the widgets
display(user_input, output_area)

Text(value='', description='Enter query:', layout=Layout(width='80%'), placeholder='Type your query here...')

Output()